export type CreatePolicyTravellerDto = {
  travellerName: string;
  passportNumber: string;
  gender?: string;
  dateOfBirth?: string;
  age?: number;
  ageOrDob?: string;
  nominee?: string;
  nomineeRelationship?: string;
  address?: string;
  pincode?: string;
  city?: string;
  district?: string;
  state?: string;
  country?: string;
  email?: string;
  mobile?: string;
  remarks?: string;
  crReferenceNumber?: string;
  pastIllness?: string;
  emergencyContactPerson?: string;
  emergencyContactNumber?: string;
  emergencyEmail?: string;
  gstNumber?: string;
  gstState?: string;
  planName?: string;
  premiumAmount?: number;
};

export type CreatePolicyDto = {
  policyNumber: string;
  partnerId: string;
  issueDate: string;
  startDate: string;
  endDate: string;
  insurerName: string;
  productCode?: string;
  travelRegion?: string;
  destination?: string;
  tripDays?: number;
  primaryTravellerName: string;
  customerEmail?: string;
  customerMobile?: string;
  premiumAmount?: number;
  travellers: CreatePolicyTravellerDto[];
};
